In [1]:
from tensorflow.keras.models import load_model, save_model

In [3]:
model = load_model('C:\\Users\\SHUBHAM SINGH\\Desktop\\AIML hackathon\\Classification\\xception_model.keras')

In [6]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [9]:
labels = ['glioma_tumor','no_tumor','meningioma_tumor','pituitary_tumor']

In [10]:
image = cv2.imread("C:\\Users\\SHUBHAM SINGH\\Desktop\\Pituitary-macroadenoma-CT-01.jpg")
image = cv2.resize(image, (150, 150))

# Normalize the image
image = image / 255.0

# Convert the image to a NumPy array and add a batch dimension
image = np.expand_dims(image, axis=0)

# Make a prediction
predictions = model.predict(image)
labels[np.argmax(predictions)]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


'meningioma_tumor'

In [11]:
image = cv2.imread("C:\\Users\\SHUBHAM SINGH\\Desktop\\images.jpg")
image = cv2.resize(image, (150, 150))

# Normalize the image
image = image / 255.0

# Convert the image to a NumPy array and add a batch dimension
image = np.expand_dims(image, axis=0)

# Make a prediction
predictions = model.predict(image)
labels[np.argmax(predictions)]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


'meningioma_tumor'

In [14]:
image = cv2.imread("C:\\Users\\SHUBHAM SINGH\\Desktop\\Testing\\pituitary_tumor\\image(45).jpg")
image = cv2.resize(image, (150, 150))
print(image)
# Normalize the image
image = image / 255.0

# Convert the image to a NumPy array and add a batch dimension
image = np.expand_dims(image, axis=0)

# Make a prediction
predictions = model.predict(image)
labels[np.argmax(predictions)]

[[[ 4  4  4]
  [ 2  2  2]
  [ 1  1  1]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 2  2  2]
  [ 1  1  1]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 2  2  2]]

 [[ 0  0  0]
  [ 3  3  3]
  [ 7  7  7]
  ...
  [ 5  5  5]
  [ 3  3  3]
  [ 5  5  5]]

 ...

 [[ 2  2  2]
  [ 5  5  5]
  [ 7  7  7]
  ...
  [ 5  5  5]
  [ 7  7  7]
  [ 8  8  8]]

 [[11 11 11]
  [11 11 11]
  [10 10 10]
  ...
  [ 0  0  0]
  [ 7  7  7]
  [10 10 10]]

 [[10 10 10]
  [11 11 11]
  [ 9  9  9]
  ...
  [ 7  7  7]
  [ 6  6  6]
  [ 4  4  4]]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


'meningioma_tumor'

In [20]:
image = cv2.imread("C:\\Users\\SHUBHAM SINGH\\Desktop\\images (1).jpg")
image = cv2.resize(image, (150, 150))

# Normalize the image
image = image / 255.0

# Convert the image to a NumPy array and add a batch dimension
image = np.expand_dims(image, axis=0)

# Make a prediction
predictions = model.predict(image)
labels[np.argmax(predictions)]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


'glioma_tumor'

In [21]:
image = cv2.imread(r"C:\Users\SHUBHAM SINGH\Desktop\imgp.jpg")
image = cv2.resize(image, (150, 150))

# Normalize the image
image = image / 255.0

# Convert the image to a NumPy array and add a batch dimension
image = np.expand_dims(image, axis=0)

# Make a prediction
predictions = model.predict(image)
labels[np.argmax(predictions)]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


'meningioma_tumor'

In [59]:
image = cv2.imread(r"C:\Users\SHUBHAM SINGH\Desktop\Testing\pituitary_tumor\image(35).jpg")
image = cv2.resize(image, (150, 150))

# Normalize the image
image = image / 255.0

# Convert the image to a NumPy array and add a batch dimension
image = np.expand_dims(image, axis=0)

# Make a prediction
predictions = model.predict(image)
labels[np.argmax(predictions)]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


'meningioma_tumor'

In [60]:
# Loop through the images
for i in range(1):  # Adjust the range as necessary to match the number of images
    # Construct the file path
    file_path = fr"C:\Users\SHUBHAM SINGH\Desktop\AIML hackathon\Classification\image(16).jpg"
    
    # Load the image
    image = cv2.imread(file_path)
    if image is None:
        print(f"Image at {file_path} could not be loaded.")
        continue
    
    # Resize the image to the required input shape
    image = cv2.resize(image, (150, 150))

    # Normalize the image
    image = image / 255.0

    # Convert the image to a NumPy array and add a batch dimension
    image = np.expand_dims(image, axis=0)

    # Make a prediction
    predictions = model.predict(image)
    
    # Interpret the model's predictions
    predicted_class = np.argmax(predictions)
    predicted_label = labels[predicted_class]
    confidence = predictions[0][predicted_class]

    # Display the results
    print(f"Image {i}: Predicted label: {predicted_label}, Confidence: {confidence * 100:.2f}%")

# Note: Adjust the range(10) to match the number of images you have


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
Image 0: Predicted label: meningioma_tumor, Confidence: 100.00%


In [61]:
# Loop through the images
for i in range(1):  # Adjust the range as necessary to match the number of images
    # Construct the file path
    file_path = fr"C:\Users\SHUBHAM SINGH\Desktop\AIML hackathon\Classification\image(77).jpg"
    
    # Load the image
    image = cv2.imread(file_path)
    if image is None:
        print(f"Image at {file_path} could not be loaded.")
        continue
    
    # Resize the image to the required input shape
    image = cv2.resize(image, (150, 150))

    # Normalize the image
    image = image / 255.0

    # Convert the image to a NumPy array and add a batch dimension
    image = np.expand_dims(image, axis=0)

    # Make a prediction
    predictions = model.predict(image)
    
    # Interpret the model's predictions
    predicted_class = np.argmax(predictions)
    predicted_label = labels[predicted_class]
    confidence = predictions[0][predicted_class]

    # Display the results
    print(f"Image {i}: Predicted label: {predicted_label}, Confidence: {confidence * 100:.2f}%")

# Note: Adjust the range(10) to match the number of images you have


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
Image 0: Predicted label: glioma_tumor, Confidence: 100.00%


In [62]:
# Loop through the images
for i in range(1):  # Adjust the range as necessary to match the number of images
    # Construct the file path
    file_path = fr"C:\Users\SHUBHAM SINGH\Desktop\AIML hackathon\Classification\image(85).jpg"
    
    # Load the image
    image = cv2.imread(file_path)
    if image is None:
        print(f"Image at {file_path} could not be loaded.")
        continue
    
    # Resize the image to the required input shape
    image = cv2.resize(image, (150, 150))

    # Normalize the image
    image = image / 255.0

    # Convert the image to a NumPy array and add a batch dimension
    image = np.expand_dims(image, axis=0)

    # Make a prediction
    predictions = model.predict(image)
    
    # Interpret the model's predictions
    predicted_class = np.argmax(predictions)
    predicted_label = labels[predicted_class]
    confidence = predictions[0][predicted_class]

    # Display the results
    print(f"Image {i}: Predicted label: {predicted_label}, Confidence: {confidence * 100:.2f}%")

# Note: Adjust the range(10) to match the number of images you have


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
Image 0: Predicted label: pituitary_tumor, Confidence: 100.00%


In [ ]:
def predcit_tumor_class(image_path):
    image = cv2.imread(image_path)
    if image is None:
        print(f"Image at {file_path} could not be loaded.")
    
    # Resize the image to the required input shape
    image = cv2.resize(image, (150, 150))

    # Normalize the image
    image = image / 255.0

    # Convert the image to a NumPy array and add a batch dimension
    image = np.expand_dims(image, axis=0)

    # Make a prediction
    predictions = model.predict(image)
    
    # Interpret the model's predictions
    predicted_class = np.argmax(predictions)
    predicted_label = labels[predicted_class]
    confidence = predictions[0][predicted_class]

    # Display the results
    print(f"Image {i}: Predicted label: {predicted_label} ")
